name: Build and package .db for dcmtk

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: DCMTK/dcmtk
          ref: master
          fetch-depth: 0
      - id: gitversion
        uses: codacy/git-version@2.4.0
        with:
          prefix: DCMTK-
          release-branch: release
          dev-branch: master
      - run: |
          sudo apt-get install -y build-essential \
            cmake \
            libpng-dev \
            libtiff-dev \
            libxml2-dev \
            libjpeg-dev \
            zlib1g-dev \
            libwrap0-dev \
            libssl-dev
      - run:  |
          mkdir ${{ github.workspace }}/dcmtk-${{ steps.gitversion.outputs.version }}-build
          cd ${{ github.workspace }}/dcmtk-${{ steps.gitversion.outputs.version }}-build
          cmake ${{ github.workspace }}
          make -j"$(($(nproc) + 1))"
          make DESTDIR=${{ github.workspace }}/dcmtk-${{ steps.gitversion.outputs.version }}-install install
      - uses: bpicode/github-action-fpm@v0.9.2
        with:
          fpm_args: 'dcmtk-${{ steps.gitversion.outputs.version }}-install'
          fpm_opts: >- 
            --input-type dir 
            --output-type deb
            --package dcmtk-bin-${{ steps.gitversion.outputs.version }}-x86_64.deb 
            --name dcmtk-bin 
            --version ${{ steps.gitversion.outputs.version }}
            --architecture x86_64
            --description 'DCMTK is a collection of libraries and applications implementing large parts the DICOM standard.'
            --url 'https://dicom.offis.de/dcmtk.php.en'
            --maintainer 'Diep Pham <diep@segmed.ai>'
      - uses: actions/github-script@v5
        if: github.ref == 'refs/heads/main'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${ context.runNumber }`,
              sha: context.sha
            })            
      - uses: ncipollo/release-action@v1.9.0
        if: github.ref == 'refs/heads/main'      
        with:
          draft: false
          allowUpdates: true
          omitBody: true
          omitName: true
          artifacts: dcmtk-bin-${{ steps.gitversion.outputs.version }}-x86_64.deb
          tag: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
  